config/routes.rb
Rails.application.routes.draw do
  
  get 'home' => 'pages#home'

  get 'help' => 'pages#help'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users

  root 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token
	before_save {self.email = self.email.downcase}
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}

	#ensure a secure passowrd for the system
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	def User.digest(string)
       cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
       BCrypt::Password.create(string, cost: cost)
	end

	#Generate a random string as remember me token
	def User.new_token
       SecureRandom.urlsafe_base64
	end

	def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
	end

	#forget a user
	def forget
        update_attribute(:remember_digest, nil)
	end

   #authenticate remember me token
   def authenticate?(remember_token)
   	  return false if remember_digest.nil?
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


  def create
  	email = params[:session][:email].downcase
  	password = params[:session][:password]
  	user = User.find_by(email: email)

  	if(user && user.authenticate(password))
  		#log the user in
  		log_in user
  		params[:session][:remember_me] == '1' ? remember(user) : forget(user)
  		redirect_to user
  	else
  	  #Create an error message
  	  flash.now[:danger] = "Invalid email/password combination"
  	  render 'new'
  	end
  end

  def destroy
     log_out if logged_in?
     redirect_to root_url
  end

  private
    def session_params
    	params.require(:session).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
    @password_confirmation = "Confirmation";
  end

  def create
   @user = User.new(user_params)
	   if(@user.save)
        #automatically log a user in
        log_in @user
        flash[:success] = "Welcome to the bookshelf dashboard"
	   	  redirect_to @user
	   else
	   	render 'new'
	   end
  end

  private

	  def user_params
	     params.require(:user).permit(:name, :email, :password, :password_confirmation)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#display page titles
	def page_title(title)
       default_title = "Welcome to Africa's best online eBook store"
       if title.empty? then default_title else title + ' | ' + default_title end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
       session[:user_id] = user.id
	end

	def remember(user)
       user.remember
       cookies.permanent.signed[:user_id] = user.id
       cookies.permanent[:remember_token] = user.remember_token
	end

	def current_user
		if(user_id = session[:user_id])
           @current_user ||= User.find_by(id: user_id)
        elsif(user_id = cookies.signed[:user_id])
        	user = User.find_by(id: user_id)
        	if (user && user.authenticated?(cookies[:remember_token]))
        		log_in user
        		@current_user = user
        	end
        end
	end

	def logged_in?
      !current_user.nil?
	end
    
    #forget a persistent session
    def forget(user)
       user.forget
       cookies.delete(:user_id)
       cookies.delete(:remember_token)
    end

	def log_out
	  forget(current_user)
      session.delete(:user_id)
      @current_user = nil
	end

end

app/helpers/users_helper.rb
module UsersHelper
	#Returns the avatar for the user
	def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: 'gravatar')
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home",   root_path %></li>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <!-- Layout -->
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do|message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <!-- Footer -->
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body class="home">

    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/help.html.erb
<% provide(:title, "Home") %>
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("brand_prlx_bg-small.jpg", alt: "Rails logo", class: "img-responsive"),
            'http://rubyonrails.org/' %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
       The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
   <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do|f| %>
         <%= render("shared/error_messages") %>
         
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control' %>

         <%= f.label :email %>
         <%= f.email_field :email, class: 'form-control' %>

         <%= f.label :password %>
         <%= f.password_field :password, class: 'form-control' %>

         <%= f.label :password_confirmation, @password_confirmation %>
         <%= f.password_field :password_confirmation, class: 'form-control' %>

         <%= f.submit "Create my account", class: "btn btn-primary" %>

      <% end %>
   </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>